package datatypes_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/reallyoldfogie/protodef-go/protocol"
	"github.com/tidwall/gjson"
)

var protoTestFiles = []struct {
	Name       string
	SchemaPath string
	TestPath   string
}{
	{Name: "conditional", SchemaPath: "../ProtoDef/schemas/conditional.json", TestPath: "../ProtoDef/test/conditional.json"},
	{Name: "datatype_tests_schema", SchemaPath: "../ProtoDef/schemas/datatype.json", TestPath: "../ProtoDef/test/datatype_tests_schema.json"},
	{Name: "numeric", SchemaPath: "../ProtoDef/schemas/numeric.json", TestPath: "../ProtoDef/test/numeric.json"},
	{Name: "structures", SchemaPath: "../ProtoDef/schemas/structures.json", TestPath: "../ProtoDef/test/structures.json"},
	{Name: "utils", SchemaPath: "../ProtoDef/schemas/utils.json", TestPath: "../ProtoDef/test/utils.json"},
}

func TestGenerateGoStructsFromProtoDef(t *testing.T) {
	// Skip: Test files in ProtoDef/test/ are test case arrays, not protocol definitions.
	// Protocol definitions require a "types" object field. Test case arrays have
	// "type" and "values" fields for each test case.
	// TODO: Either create proper protocol files or rewrite to generate from test cases
	t.Skip("Test files contain test case arrays, not protocol definitions")

	for _, test := range protoTestFiles {
		jsonData, err := os.ReadFile(test.TestPath)
		if err != nil {
			t.Errorf("failed to read test file %s: %v", test.TestPath, err)
			continue
		}

		// Parse the protocol JSON using the existing Protocol loader
		var proto protocol.Protocol
		result := gjson.ParseBytes(jsonData)
		err = proto.ReadJSON(result)
		if err != nil {
			t.Errorf("failed to parse protocol for %s: %v", test.Name, err)
			continue
		}

		// Generate Go code for each type in the protocol
		var code strings.Builder
		code.WriteString("// Code generated by TestGenerateGoStructsFromProtoDef. DO NOT EDIT.\n")
		code.WriteString("package generated\n\n")
		for _, typ := range proto.Types {
			code.WriteString(goStructForType(typ))
		}

		goFilePath := filepath.Join("../generated", test.Name+".go")
		err = os.WriteFile(goFilePath, []byte(code.String()), 0644)
		if err != nil {
			t.Errorf("failed to write generated Go file for %s: %v", test.Name, err)
			continue
		}
		fmt.Printf("Generated: %s\n", goFilePath)
	}
}

// goStructForType generates a Go struct definition for a ProtoDef type (simplified for demo)
func goStructForType(typ any) string {
	t, ok := typ.(interface{ GetName() string })
	if !ok || t.GetName() == "" {
		return ""
	}
	name := t.GetName()
	if len(name) > 0 {
		name = strings.ToUpper(name[:1]) + name[1:]
	}
	return fmt.Sprintf("type %s struct {\n\t// TODO: fill fields based on ProtoDef type\n}\n\n", name)
}
